FROM golang:1.18.6-alpine3.16 AS builder
RUN apk --no-cache add git make bash
RUN git config --global http.version HTTP/1.1
ADD . /go/src/github/csi-node-driver-registrar
WORKDIR /go/src/github/csi-node-driver-registrar
RUN make

FROM gcr.io/distroless/static:latest
LABEL maintainers="Kubernetes Authors"
LABEL description="CSI Node driver registrar"

COPY --from=builder /go/src/github/csi-node-driver-registrar/bin/csi-node-driver-registrar csi-node-driver-registrar
ENTRYPOINT ["/csi-node-driver-registrar"]
