name: Build x86 and arm Image

on:
  pull_request:
    branches:
      - exc-*
  push:
    branches:
      - ecx-*
env:
  VERSION: 2.1

jobs:
  #  docker-image-2-0:
  #    name: v2.0
  #    if: github.event_name == 'push' && contains(github.ref, 'v2.0.')
  #    runs-on: ubuntu-18.04
  #    env:
  #      IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/linux:2.0
  #    steps:
  #    - uses: actions/checkout@v1
  #      with:
  #        fetch-depth: 1
  #    - name: Build & Push
  #      run: |
  #        docker login docker.pkg.github.com -u owner -p ${{ secrets.GITHUB_TOKEN }}
  #        docker build -t $IMAGE_NAME docker/linux/2.0/
  #        docker push $IMAGE_NAME
  #    timeout-minutes: 10
  docker-image:
    name: Build x86 and arm Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker image
        run: docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/csi-node-driver-registrar:$VERSION -f docker/linux/2.01/Dockerfile --push --platform=linux/arm64,linux/amd64 .